# -*- coding: utf-8 -*-
"""ejercicio2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yE2UYnodqPDugMatmm9Dx1Ik9Yo6alO
"""

pip install spanlp

from spanlp.palabrota import Palabrota

validador = Palabrota(censor_char="*")

print(validador.contains_palabrota("hola mierda como estas?"))
print(validador.censor("hola mierda como estas?"))